development:
  adapter: mysql2
  encoding: utf8
  database: replicator_development
  pool: 10
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: replicator_test
  pool: 5
  username: root
  password: